kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp-deployment
  namespace: webapp-namespace
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: webapp-pod
      namespace: webapp-namespace
      labels: 
       app: webapp
    spec: 
      containers:
      - name: webapp-container
        image: sweta160431/webapp
        ports:
          - containerPort: 5000
