kind: Service
apiVersion: v1
metadata:
  name: webapp-service
  namespace: webapp-namespace
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 5000
  type: LoadBalancer
